import type { IconSvgElement } from '@hugeicons/react'
import {
  Airplane01Icon,
  Baby01Icon,
  BaseballBatIcon,
  Basketball01Icon,
  BeachIcon,
  BeerIcon,
  Bicycle01Icon,
  Book01Icon,
  Briefcase01Icon,
  Building01Icon,
  Bus01Icon,
  Camera01Icon,
  Car01Icon,
  CatIcon,
  Chair01Icon,
  ChartUpIcon,
  Clock01Icon,
  Coffee01Icon,
  DollarCircleIcon,
  DrinkIcon,
  Dumbbell01Icon,
  FavouriteCircleIcon,
  Film01Icon,
  Fire02Icon,
  FlashIcon,
  FlowerIcon,
  FootballIcon,
  GamepadDirectionalIcon,
  GiftCardIcon,
  GolfBallIcon,
  GraduationCapIcon,
  HandBag01Icon,
  HeadphonesIcon,
  Home01Icon,
  Hospital01Icon,
  Hotel01Icon,
  Idea01Icon,
  Key01Icon,
  LibraryIcon,
  LoyaltyCardIcon,
  Luggage01Icon,
  Medal01Icon,
  Medicine01Icon,
  MoneyBag01Icon,
  Motorbike01Icon,
  MusicNote01Icon,
  ParkingAreaCircleIcon,
  Passport01Icon,
  PiggyBankIcon,
  PillBottleIcon,
  Pizza01Icon,
  Recycle01Icon,
  RepeatIcon,
  Restaurant01Icon,
  Rocket01Icon,
  School01Icon,
  ScissorIcon,
  Shapes01Icon,
  Shirt01Icon,
  ShoppingBag01Icon,
  ShoppingBasket01Icon,
  SmartPhone01Icon,
  Sofa01Icon,
  StethoscopeIcon,
  Store01Icon,
  Sun01Icon,
  SwimmingCapIcon,
  Tag01Icon,
  Taxi02Icon,
  TennisBallIcon,
  Ticket01Icon,
  ToyBrickIcon,
  Train01Icon,
  Tree01Icon,
  TruckDeliveryIcon,
  UmbrellaDollarIcon,
  UniversityIcon,
  Video01Icon,
  Wallet01Icon,
  WashingMachineIcon,
  Wifi01Icon,
  Yoga01Icon,
} from '@hugeicons/core-free-icons'

// RN-029 — catálogo cerrado de íconos para categorías (biblioteca gráfica, no emoji). `generic`
// es el ícono por defecto (DEFAULT_CATEGORY_ICON en lib/categories.ts) cuando el usuario no elige
// uno. Sin referencia de Figma para este catálogo — selección razonable de Hugeicons, agrupada por
// tema para que el picker se navegue con más facilidad.
export const CATEGORY_ICON_CATALOG: { key: string; label: string; icon: IconSvgElement }[] = [
  // Vivienda y servicios
  { key: 'home', label: 'Home', icon: Home01Icon },
  { key: 'key', label: 'Rent', icon: Key01Icon },
  { key: 'bolt', label: 'Electricity', icon: FlashIcon },
  { key: 'fire', label: 'Gas', icon: Fire02Icon },
  { key: 'wifi', label: 'Internet', icon: Wifi01Icon },
  { key: 'phone', label: 'Phone', icon: SmartPhone01Icon },
  { key: 'sofa', label: 'Furniture', icon: Sofa01Icon },
  { key: 'chair', label: 'Home goods', icon: Chair01Icon },
  { key: 'washing', label: 'Laundry', icon: WashingMachineIcon },
  { key: 'building', label: 'Real estate', icon: Building01Icon },

  // Comida y bebida
  { key: 'cart', label: 'Groceries', icon: ShoppingBasket01Icon },
  { key: 'utensils', label: 'Dining', icon: Restaurant01Icon },
  { key: 'pizza', label: 'Fast food', icon: Pizza01Icon },
  { key: 'coffee', label: 'Coffee', icon: Coffee01Icon },
  { key: 'drink', label: 'Drinks', icon: DrinkIcon },
  { key: 'beer', label: 'Bar', icon: BeerIcon },

  // Transporte
  { key: 'car', label: 'Transport', icon: Car01Icon },
  { key: 'bus', label: 'Bus', icon: Bus01Icon },
  { key: 'train', label: 'Train', icon: Train01Icon },
  { key: 'taxi', label: 'Taxi', icon: Taxi02Icon },
  { key: 'bicycle', label: 'Bicycle', icon: Bicycle01Icon },
  { key: 'motorbike', label: 'Motorbike', icon: Motorbike01Icon },
  { key: 'truck', label: 'Delivery', icon: TruckDeliveryIcon },
  { key: 'parking', label: 'Parking', icon: ParkingAreaCircleIcon },

  // Compras
  { key: 'handbag', label: 'Shopping', icon: HandBag01Icon },
  { key: 'shoppingbag', label: 'Retail', icon: ShoppingBag01Icon },
  { key: 'shirt', label: 'Clothes', icon: Shirt01Icon },
  { key: 'tag', label: 'Other', icon: Tag01Icon },
  { key: 'store', label: 'Store', icon: Store01Icon },

  // Salud
  { key: 'heart', label: 'Health', icon: FavouriteCircleIcon },
  { key: 'hospital', label: 'Hospital', icon: Hospital01Icon },
  { key: 'stethoscope', label: 'Doctor', icon: StethoscopeIcon },
  { key: 'medicine', label: 'Medicine', icon: Medicine01Icon },
  { key: 'pill', label: 'Pharmacy', icon: PillBottleIcon },

  // Entretenimiento
  { key: 'film', label: 'Entertainment', icon: Film01Icon },
  { key: 'video', label: 'Streaming', icon: Video01Icon },
  { key: 'music', label: 'Music', icon: MusicNote01Icon },
  { key: 'gamepad', label: 'Gaming', icon: GamepadDirectionalIcon },
  { key: 'ticket', label: 'Tickets', icon: Ticket01Icon },
  { key: 'headphones', label: 'Audio', icon: HeadphonesIcon },
  { key: 'camera', label: 'Photography', icon: Camera01Icon },

  // Finanzas
  { key: 'wallet', label: 'Income', icon: Wallet01Icon },
  { key: 'dollar', label: 'Finance', icon: DollarCircleIcon },
  { key: 'moneybag', label: 'Savings', icon: MoneyBag01Icon },
  { key: 'piggybank', label: 'Piggy bank', icon: PiggyBankIcon },
  { key: 'trend-up', label: 'Investment', icon: ChartUpIcon },
  { key: 'repeat', label: 'Subscriptions', icon: RepeatIcon },
  { key: 'umbrella', label: 'Insurance', icon: UmbrellaDollarIcon },
  { key: 'loyalty', label: 'Rewards', icon: LoyaltyCardIcon },
  { key: 'gift', label: 'Gifts', icon: GiftCardIcon },

  // Viajes
  { key: 'plane', label: 'Travel', icon: Airplane01Icon },
  { key: 'luggage', label: 'Luggage', icon: Luggage01Icon },
  { key: 'passport', label: 'Passport', icon: Passport01Icon },
  { key: 'hotel', label: 'Hotel', icon: Hotel01Icon },
  { key: 'beach', label: 'Vacation', icon: BeachIcon },

  // Educación y trabajo
  { key: 'book', label: 'Education', icon: Book01Icon },
  { key: 'school', label: 'School', icon: School01Icon },
  { key: 'university', label: 'University', icon: UniversityIcon },
  { key: 'graduation', label: 'Graduation', icon: GraduationCapIcon },
  { key: 'library', label: 'Books', icon: LibraryIcon },
  { key: 'briefcase', label: 'Work', icon: Briefcase01Icon },
  { key: 'idea', label: 'Ideas', icon: Idea01Icon },
  { key: 'rocket', label: 'Startup', icon: Rocket01Icon },

  // Deporte y bienestar
  { key: 'dumbbell', label: 'Fitness', icon: Dumbbell01Icon },
  { key: 'yoga', label: 'Yoga', icon: Yoga01Icon },
  { key: 'football', label: 'Soccer', icon: FootballIcon },
  { key: 'basketball', label: 'Basketball', icon: Basketball01Icon },
  { key: 'baseball', label: 'Baseball', icon: BaseballBatIcon },
  { key: 'tennis', label: 'Tennis', icon: TennisBallIcon },
  { key: 'golf', label: 'Golf', icon: GolfBallIcon },
  { key: 'swim', label: 'Swimming', icon: SwimmingCapIcon },

  // Familia y otros
  { key: 'baby', label: 'Baby', icon: Baby01Icon },
  { key: 'cat', label: 'Pets', icon: CatIcon },
  { key: 'toy', label: 'Toys', icon: ToyBrickIcon },
  { key: 'scissor', label: 'Salon', icon: ScissorIcon },
  { key: 'medal', label: 'Achievements', icon: Medal01Icon },
  { key: 'sun', label: 'Outdoors', icon: Sun01Icon },
  { key: 'tree', label: 'Nature', icon: Tree01Icon },
  { key: 'flower', label: 'Flowers', icon: FlowerIcon },
  { key: 'clock', label: 'Time', icon: Clock01Icon },
  { key: 'recycle', label: 'Recycling', icon: Recycle01Icon },

  { key: 'generic', label: 'Generic', icon: Shapes01Icon },
] as const

export function getCategoryIcon(key: string | null | undefined): IconSvgElement {
  return CATEGORY_ICON_CATALOG.find((entry) => entry.key === key)?.icon ?? Shapes01Icon
}
